/**
 * @itqan/quran-data — bundled, offline-first Quran content.
 *
 * Data is generated by `scripts/generate.mjs` from the AlQuran Cloud API and shipped
 * as JSON under `data/`. This module exposes the bundled shapes and edition metadata.
 *
 * NOTE: the large arrays (`ayahs.json`, translations) are intentionally NOT imported
 * here — that would force tsc/Metro to inline ~2MB into every consumer's type graph.
 * The app loads them lazily via the `@itqan/quran-data/data/*` export path when seeding
 * its local SQLite database. See `apps/mobile/src/db`.
 */
import type { MushafScript, RevelationType } from '@itqan/types';
import metaJson from '../data/meta.json';

/** A surah record as bundled in `data/surahs.json`. */
export interface BundledSurah {
  number: number;
  nameArabic: string;
  nameSimple: string;
  nameEnglish: string;
  revelationType: RevelationType;
  ayahCount: number;
  bismillahPre: boolean;
}

/** An ayah record as bundled in `data/ayahs.json`. */
export interface BundledAyah {
  key: string;
  surah: number;
  ayah: number;
  /** Uthmani text, basmala stripped from ayah 1 (rendered as a header instead). */
  text: string;
  page: number;
  juz: number;
  hizb: number;
  rub: number;
  sajda: 'recommended' | 'obligatory' | null;
}

/** A page/juz boundary record (`data/pages.json`, `data/juz.json`). */
export interface BundledBoundary {
  number: number;
  firstAyahKey: string;
  lastAyahKey: string;
  juzNumber?: number;
  lineCount?: number;
}

/** A translation file is a flat map of `"<ayahKey>" -> text` (`data/translations/*.json`). */
export type BundledTranslation = Record<string, string>;

export interface QuranDataMeta {
  version: string;
  generatedAt: string;
  source: string;
  textEdition: string;
  editions: TranslationEdition[];
  counts: { surahs: number; ayahs: number; pages: number; juz: number };
}

export interface TranslationEdition {
  id: string;
  language: string;
  name: string;
}

/** Bundled metadata (small — safe to import statically). */
export const meta = metaJson as QuranDataMeta;

/** The default Mushaf script bundled in R1. */
export const DEFAULT_SCRIPT: MushafScript = 'uthmani';

/** The translation editions available offline. */
export const TRANSLATION_EDITIONS: TranslationEdition[] = meta.editions;

/**
 * Resolve a bundled JSON asset path for `require`/Metro `require` at runtime.
 * Consumers should `require('@itqan/quran-data/data/ayahs.json')` directly so the
 * bundler can statically include the asset.
 */
export const DATA_FILES = {
  surahs: 'surahs.json',
  ayahs: 'ayahs.json',
  pages: 'pages.json',
  juz: 'juz.json',
  translation: (editionId: string) => `translations/${editionId}.json`,
} as const;
